baseURL = "https://faizanmohd5.github.io/my-blog-website/"
relativeURLs = true
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = true
buildFuture = false
buildExpired = false
# googleAnalytics = ""
pygmentsUseClasses = true
publishDir = "docs"

[minify]
disableXML = true
minifyOutput = true

[taxonomies]
tag = "tags"

[params]
env = "production"
title = "Faizan"
description = "Welcome to my Blog website which I created for uploading all my last hopes for getting a job being a final year student!"
keywords = [
    "Software Engineer",
    "Programming",
    "Web Development",
    "Django",
    "Python",
    "Go",
    "Hugo",
    "JavaScript",
    "DSA",
    "tech for kids",
    "programming tips",
    "projects",
    "gfg160",
    "leetcode",
    "geeks2024",
    "Tech Blog",
    "Portfolio",
    "Coding Tutorials",
    "Software Development",
    "Tech Trends",
    "Web Designer",
    "Freelance Developer",
    "Open Source Projects",
    "Data Science",
    "AI",
    "Latest tech trends in 2024",
    "Building a portfolio website for developers",
    "Creating effective coding tutorials",
    "The future of software engineering",
    "AI applications in web development",
    "gohugoio"
]
author = "Faizan"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

  [params.assets]
  favicon = "/favicon.ico"
  favicon16x16 = "/favicon-16x16.png"
  favicon32x32 = "/favicon-32x32.png"
  apple_touch_icon = "/apple-touch-icon.png"
  safari_pinned_tab = "/favicon-16x16.png"

  [params.label]
  text = "My Blogs"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "Faizan"
  subtitle = "This is subtitle"
  imageUrl = "linkedinprofile.jpg"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hello!, I'm Faizan! 💫"
  Content = "Grab a seat. Dive into my blog. You’ll find coding tips, tech trends, and maybe a couple of memes to make this all a bit more bearable."

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/faizanmohd5"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/farukhfaizan/"

  [[params.socialIcons]]
  name = "X"
  url = "https://x.com/thehumbledone_1"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "archive"
name = "archive"
url = "/archive/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "search"
name = "search"
url = "/search/"
weight = 40

[markup.highlight]
noClasses = false

[outputs]
home = [ "HTML", "RSS", "JSON" ]